"""add_file_hash_fix_file_size_bytes

Revision ID: 2c5f3091dea7
Revises: a3f9c1d2e456
Create Date: 2026-08-31 18:52:02.958666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c5f3091dea7'
down_revision: Union[str, Sequence[str], None] = 'a3f9c1d2e456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationships', 'explanation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_unique_constraint('uq_relationship_pair_type', 'relationships', ['source_id', 'target_id', 'rel_type'])
    op.add_column('screenshots', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.alter_column('screenshots', 'file_size_bytes',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='file_size_bytes::integer')
    op.create_index(op.f('ix_screenshots_file_hash'), 'screenshots', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_file_hash'), table_name='screenshots')
    op.alter_column('screenshots', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('screenshots', 'file_hash')
    op.drop_constraint('uq_relationship_pair_type', 'relationships', type_='unique')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.alter_column('relationships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('relationships', 'explanation',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
