"""add_app_detected_captured_at_domain_to_memories

Revision ID: 2c766c3a59a7
Revises: 2c5f3091dea7
Create Date: 2026-08-31 18:59:02.358294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c766c3a59a7'
down_revision: Union[str, Sequence[str], None] = '2c5f3091dea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('app_detected', sa.String(length=256), nullable=True))
    op.add_column('memories', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memories', sa.Column('domain', sa.String(length=256), nullable=True))
    op.alter_column('memories', 'embedding_placeholder',
               existing_type=sa.TEXT(),
               comment='Placeholder — Phase C migrates this to vector(768)',
               existing_comment='Placeholder for pgvector embedding — Phase 7 will migrate this to vector(1536)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'embedding_placeholder',
               existing_type=sa.TEXT(),
               comment='Placeholder for pgvector embedding — Phase 7 will migrate this to vector(1536)',
               existing_comment='Placeholder — Phase C migrates this to vector(768)',
               existing_nullable=True)
    op.drop_column('memories', 'domain')
    op.drop_column('memories', 'captured_at')
    op.drop_column('memories', 'app_detected')
    # ### end Alembic commands ###
